### ISSUE TITLE
Loading package.json from modules as './package'

### ISSUE THREAD

**Issue by jacob414** [rocjs/roc#111]
Hello,

(Trying to use Roc.js /w [enzyme](https://github.com/airbnb/enzyme), using the same sources for browser-based tests as for Node.js based ones)

I'm having an issue with a module ([cheerio](https://github.com/cheeriojs/cheerio)) that tries to get it's version like this:

``` javascript
version = require('./package').version
```

(Specifically, [this](https://github.com/cheeriojs/cheerio/issues/836) issue)

Solutions suggested involves tweaking WebPack config to load the `package.json` file from the name `'./package'`, but you normally don't your own `webpack.config.js` in Roc?

The issue is already fixed upstream in Cheerio, but haven't been released to NPM yet, and when that happens, Enzyme will need to update it's dependency too. Is there a quick way to make the Roc WebPack config load modules without the `.json` extension being explicitly set?

Thanks in advance!

**Comment by dlmr** [comment]
Hi!

You can definitely modify the Webpack configuration when using Roc but it is not as transparent as normally. 

There is one way to do it now and we will soon have a much better syntax when we release `1.0.0` as stable in the near future. This will be documented in great detail. =)

For now you can do this in your project and it should work. Please get back to me if there is any problems when testing this since I have not yet tried it. 

Since this will change a bit in the future I will not give a detailed explanation about how/why this works, but you can read a bit about it [here (about action is general)](https://github.com/rocjs/roc/blob/master/docs/Extensions.md#actions) and [here (about the specific hook we use)](https://github.com/rocjs/roc-package-webpack/blob/master/packages/roc-package-webpack-dev/docs/Hooks.md#build-webpack) and [here (Webpack documentation)](https://webpack.github.io/docs/configuration.html#resolve-extensions).

``` javascript
// roc.config.js
module.exports = {
    settings: { /* ...*/ },
    action: () => (rocObject) => {
        const hook = rocObject.hook;
        const rocBuilder = rocObject.previousValue;
        if (hook === 'build-webpack') {
            return () => () => {
                rocBuilder.buildConfig.resolve.extensions = ['', '.js', '.json'];
                return rocBuilder;
            };
        }
    }
};
```
