### ISSUE TITLE
Redux middlewares?

### ISSUE THREAD

**Issue by jacob414** [rocjs/roc#113]
Hello, me again I'm afraid (just a question this time),

Is there a way to run redux middlewares, and in that case how? (I saw a mention of a file `redux-middlewares.js` in the source code, took a chance an created one in my `redux/` directory of my Roc project, but it didn't seem to be imported). I'm looking at running `redux-saga` in my project, and the [docs](http://yelouafi.github.io/redux-saga/) tells me to install the middleware in the `createStore()` call for Redux.

**Comment by dlmr** [comment]
You can add Redux middlewares as you tried to do but the file you mentioned, `redux-middlewares.js`, will be resolved against the root of the project. You can change this by setting the following in the settings.

**Example**

``` javascript
settings: {
  build: {
    reduxMiddlewares: 'redux/middlewares.js'
  }
}
```

However, that will not work with `redux-saga` since it requires some additional things to function as you mentions. Currently will you need to do the [following in your project](https://github.com/rocjs/roc-package-web-app-react/issues/21#issuecomment-229931372) to go around this and we are working on making this better in a [coming release of `roc-package-web-app-react`](https://github.com/rocjs/roc-package-web-app-react/commit/13f86faefe39d6a172b488adfdb72c16af5dddd3) and you can [use the branch](https://github.com/rocjs/roc-package-web-app-react/tree/feature/redux-saga) in the meantime as an alternative but it is not fully completed yet and your milage may vary.

**Comment by jacob414** [comment]
It's possible, also with saga, I just made a successful end-to-end ("some assembly required" as you'll see):
- I added a `settings` entry as you described.
- My `redux/middlewares.js` looks like this:

``` javascript
import createSagaMiddleware from 'redux-saga'

const sagaMiddleware = createSagaMiddleware();

const middlewares = [sagaMiddleware];

export { sagaMiddleware }; // <- this will make the middleware reachable

export default function() {
  return middlewares;
}
```
- In a component where I want to trigger sagas, I install & start the saga once using Lodash `once()`, and triggers that in the components `render()` method:

``` javascript
import { once } from 'lodash';

import * as saga from 'redux-saga'

import * as effect from 'redux-saga/effects';

// From export in prev. code, middleware accessible as middleware.sagaMiddleware now:
import * as middlewares from '../../redux/middlewares.js';

// ...

function doFetching(param) {
  console.log('SAGA doFetching..', param);
  return Promise.resolve('*P*');
}

function *doAuth(action) {
  console.log('SAGA doAuth REQUESTED.', action);
  const res = yield effect.call(doFetching, '*param*')
  console.log('FAKE FETCHING RESPONSE', res);
}

function *mySaga() {
  yield saga.takeEvery('auth!', doAuth);
}

function installSaga() {
  console.log('Installing saga middleware..');
  middlewares.sagaMiddleware.run(mySaga)
}

const installSagaOnce = once(installSaga);

// ...

    render() {
      // ...
      installSagaOnce();
```
- After that, I was able to send a Redux action that triggered the proof-of-concept saga (a no-op for starters)
- When triggered an action along the lines of  `{type: 'auth!', ...}` could see the following in my DevTools console:

```
SAGA doAuth REQUESTED.
Object {type: "auth!", ... }
SAGA doFetching.. *param*
FAKE FETCHING RESPONSE *P*
```

\o/

**Comment by dlmr** [comment]
Awesome that you found a way to solve this! 👍 

I will close this issue for now and we should soon add/look into add first class support for `redux-saga` in Roc now that we are almost ready to publish the new version.
