### ISSUE TITLE
Programmatic route change

### ISSUE THREAD

**Issue by jacob414** [rocjs/roc#114]
Hello again, another question,

I'm looking for ways to programmatically switch between routes. I made a quick end-to-end in the `Start` component, where I put an `onClick()` handler on an `A` like this to try:

``` jsx
  render() {
    const self = this;
    // ..
      <a href="#"
               onClick={(event) => {
                   self.props.history.replace('/about/'); // Found .props.history.transitionTo() using DevTools
                   event.preventDefault();
                 } }>Go to place
            </a>
```

Running the code gave a warning:

```
common.js:45 Warning: [react-router] `props.history` and `context.history` are deprecated. Please use `context.router`. http://tiny.cc/router-contextchanges
```

But worked. I went looking for `.context.router`, but:

```
> self.context.router
undefined
```

I can continue without problems to use the `.replace()` function I found, but is there a more correct that I have missed?

**Comment by dlmr** [comment]
In React you need to tell a component what it should read from context, you will not have access to it automatically. You can read more about this [here](https://facebook.github.io/react/docs/context.html).

As mentioned in the link that you get from the error there is a higher order component that can be used to easily get access to the context as a prop, `withRouter`. The problem with that however is that `roc-package-web-app-react` currently uses `~2.3.0` and not `~2.4.0`, meaning that `withRouter` is not available. We are in the process of updating how we manage dependencies like `react-router` that will make it easier for us to keep version up to date. If there is a immediate need I can update the `roc-package-web-app-react` to use the latest version of `react-router`, otherwise it will come soon with the new improved core.

An alternative way to do this, change the location, is to use [`react-router-redux`](https://github.com/reactjs/react-router-redux) as can be seen [here](https://github.com/reactjs/react-router-redux#pushlocation-replacelocation-gonumber-goback-goforward).
