### ISSUE TITLE
"Packages" are too generic names

### ISSUE THREAD

**Issue by alexewerlof** [rocjs/roc#117]
Python has “eggs”, Ruby has “gems”, npm has “packages”, Roc has …?

_Egg_ would be something, since _Roc_ is a bird but @dlmr said it was used before and changed to _package_ to be more expressive. But I think _package_ is a term that is overused as well. Especially in the NPM world package has a meaning that is not neatly overlapping with a _Roc_ package. We shouldn't be shy about creating new names. Check out "[duck](https://github.com/erikras/ducks-modular-redux)" for example.

_[Yolk](https://en.wikipedia.org/wiki/Yolk)_ could be another idea?

> The yolk in an egg is material of which the primary function is to supply food for the development of the animal embryo.

Could be nice to have a name that is easy to search and is specific enough to immediately click with Roc users. It can also be cool if the name is a bit fun and playful. Any thoughts? 💭

**Comment by theneva** [comment]
How about pebbles? They're small roc(k)s...

**Comment by dlmr** [comment]
The most important thing for me in regards to naming things is that the names we use make it easier for users to understand Roc. I agree that we should consider replacing packages with something else if it prevents this.

As I mentioned above, we had in one early version something called `eggs` and related methods named `brood`  and `hatch` ( a bit much maybe). We eventually replaced it with more common names to make it easier for users to understand Roc quickly, at least that was the idea. The reasoning was that everyone knows what a package is without having to explain new concepts, a "box" of logic, code and other stuff. Something that we did not however consider enough, I guess, is the potential confusion when a user has a concept of what a package is that does not match accurately enough against Roc. Additionally some confusion can definitely be had around that _all_ Roc packages are npm packages but not all npm packages are Roc packages.

One reason why this also might seem more important that it is could be the lack of good documentation, something that has been updated recently on the next branch. It could be the case that the current name works as long as we have documentation that explains what a Roc package is and what it is not. Something that we would need if we go for a "playful" name as well. 

Personally I'm not sure if another name is needed but I'm not the "target user" here either. I think we will need more input around this to make sure we make the right decision.

This should be resolved before we release the final 1.0.0 since it will have breaking changes.

**Comment by alexewerlof** [comment]
> all Roc packages are npm packages but not all npm packages are Roc packages.

Guess some Roc packages can also be just Github repos (ie. not registered at npm)?

**Comment by dlmr** [comment]
@userpixel You can point to any directory as a package but you will need some way to get it to your hard drive, npm is strongly recommend since Roc does not provide an alternative way.

You might be thinking about templates that are downloaded from Github by default and should never, as of now, be published to npm.

**Comment by dlmr** [comment]
Any more thoughts about this?

Personally I think `packages` & `plugins` works quite well and maybe we just need to focus on the documentation and make it clear what they are and the differences between them along with npm packages.

**Comment by Reasonable-Solutions** [comment]
I have only one opinion on this: 
Please avoid cutesy metaphors.

**Comment by alexewerlof** [comment]
@dlmr let's not delay the release for this one.

> maybe we just need to focus on the documentation and make it clear what they are and the differences between them along with npm packages.

🔨
