### ISSUE TITLE
react and babel errors

### ISSUE THREAD

**Issue by detra** [rocjs/roc#124]
when using 'roc dev'  get the following errors:

`ERROR in ./~/react-pure-render/function.js
Module build failed: ReferenceError: [BABEL] ... Using removed Babel 5 option: ...`

`ERROR in ./~/redux-devtools-themes/lib/index.js
Module build failed: ReferenceError: [BABEL] ... Using removed Babel 5 option: ...`

**Comment by dlmr** [comment]
This happens because both of those modules have published their `.babelrc` to npm that are using Babel 5. Roc uses Babel 6 internally and will try to load the configuration it finds in `.babelrc` files which in this case creates the error you are experiencing. 

It would be optimal here if both of those modules would not publish their `.babelrc` to npm but that would not solve the immediate problem here. :) 

We can tell Roc to ignore these files but it might be better to use alternative modules instead in this case.

`react-pure-render` has been deprecated and I suggest an alternative module https://github.com/gaearon/react-pure-render#no-maintenance-intended like https://www.npmjs.com/package/react-addons-shallow-compare

`redux-devtools-themes` will most often not be needed in a Roc project, you can change the theme directly with `dev.reduxDevtools.theme` in `roc.config.js`. https://github.com/rocjs/roc-package-web-app-react/blob/master/packages/roc-package-web-app-react-dev/docs/Settings.md#reduxdevtools

**Comment by detra** [comment]
Thanks @dlmr for reply and advice on alternatives/fixes
Worked at it a bit more, my workaround for now was to update the babel 5 config to the new babel 6 'plugin' syntax.

getting other other errors .. will post in a bit
