### ISSUE TITLE
running npm install in new app folder installs local version of roc

### ISSUE THREAD

**Issue by devdavidkarlsson** [rocjs/roc#130]
Why have a local roc version when you already have been asked to install one globally?
I would prefer to have one local only and not updating my system using "sudo" when installing roc.

**Comment by andreasrs** [comment]
Hey! The global one is for convenience when `new`ing or `init`ing new projects.

The local one will always be preferred when available, even when triggered through the global instance. Roc makes sure of this. It prints a notice when detecting a local instance which is used instead, in a project.

Not directly related to this issue, but it is often preferred to set up npm so that no sudo is required for "global" (-g) installs. This is done by making it "global" to your particular user, and not entire multiuser system which resides in locations that require root.

**Comment by dlmr** [comment]
I will go ahead and close this issue. 

If you have additional questions or problems please open another issue! :)
