### ISSUE TITLE
Unable to initialise web-app-react

### ISSUE THREAD

**Issue by papucho** [rocjs/roc#98]
Hi,

Following the instructions on the site, I get: 

```
$ roc init web-app-react

An error occured during init!

Response code 403 (Forbidden)
```

Am I missing something?

**Comment by dlmr** [comment]
We are using the Github API to fetch the available versions of the template, so it might be the case that your IP has been throttled by Github. 

if you access this https://api.github.com/repos/rocjs/roc-template-web-app-react/tags directly I assume you still get `403`. This is probably because your IP has reached its rate limit as described [here](https://developer.github.com/v3/#rate-limiting).

To directly verify you can go here an check: https://api.github.com/rate_limit 

So to avoid this issue currently you would need to run the command from another IP or [just download the template manually from Github](https://github.com/rocjs/roc-template-web-app-react) and update the following files manually inside the `template` folder to not have any `{{ }}` handlebars. You only need the files inside the template folder, that is the actual template.
- `package.json`
- `roc.config.js` 

Try that and if there is any more problems I'm more than happy to help!

In the future we could implement a fallback if this occurs.

Edit: I should add that you should verify the links when your are not logged into Github or using a incognito browser session since Github allows more requests when you are authenticated. Something that you are not when using `roc init` or `roc new`.

**Comment by andreasrs** [comment]
Assuming that the suggestions from DLMR were correct and that you were throttled by Github in this case. Let us know if you have more questions!

**Comment by schibsted-martin** [comment]
I hit the limit fairly quick and it is pretty annoying to be honest. Is there really no other way than doing the manual download? I.e passing credentials with the `roc new` command?

**Comment by dlmr** [comment]
I guess the reason that you hit the limit is because your share the same IP with several other users or doing something else using the API. I think this is quite uncommon in most situations.

We could/should have a fallback when we get a 403 and circumvent the API by directly downloading what we need.
